import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../features/booking/domain/booking.dart';
import '../../../features/booking/domain/service_package.dart';
import '../../../features/profile/domain/vehicle.dart';
import '../data/booking_repository.dart';
import '../../auth/data/auth_repository.dart';

class BookingState {
  final int currentStep;
  final List<ServicePackage> selectedServices;
  final Vehicle? selectedVehicle;
  final DateTime? selectedDate;
  final DateTime? selectedTimeSlot;
  final bool isLoading;
  final String? error;

  BookingState({
    this.currentStep = 0,
    this.selectedServices = const [],
    this.selectedVehicle,
    this.selectedDate,
    this.selectedTimeSlot,
    this.isLoading = false,
    this.error,
  });

  double get totalPrice =>
      selectedServices.fold(0, (sum, service) => sum + service.price);

  BookingState copyWith({
    int? currentStep,
    List<ServicePackage>? selectedServices,
    Vehicle? selectedVehicle,
    DateTime? selectedDate,
    DateTime? selectedTimeSlot,
    bool? isLoading,
    String? error,
  }) {
    return BookingState(
      currentStep: currentStep ?? this.currentStep,
      selectedServices: selectedServices ?? this.selectedServices,
      selectedVehicle: selectedVehicle ?? this.selectedVehicle,
      selectedDate: selectedDate ?? this.selectedDate,
      selectedTimeSlot: selectedTimeSlot ?? this.selectedTimeSlot,
      isLoading: isLoading ?? this.isLoading,
      error: error,
    );
  }
}

class BookingController extends AutoDisposeNotifier<BookingState> {
  @override
  BookingState build() {
    return BookingState();
  }

  void toggleService(ServicePackage service) {
    final currentServices = List<ServicePackage>.from(state.selectedServices);
    if (currentServices.contains(service)) {
      currentServices.remove(service);
    } else {
      currentServices.add(service);
    }
    state = state.copyWith(selectedServices: currentServices);
  }

  void selectVehicle(Vehicle vehicle) {
    state = state.copyWith(selectedVehicle: vehicle);
    nextStep();
  }

  void selectDate(DateTime date) {
    state = state.copyWith(selectedDate: date);
  }

  void selectTimeSlot(DateTime time) {
    state = state.copyWith(selectedTimeSlot: time);
  }

  void nextStep() {
    if (state.currentStep < 3) {
      state = state.copyWith(currentStep: state.currentStep + 1);
    }
  }

  void previousStep() {
    if (state.currentStep > 0) {
      state = state.copyWith(currentStep: state.currentStep - 1);
    }
  }

  Future<void> confirmBooking() async {
    final user = ref.read(authRepositoryProvider).currentUser;
    if (user == null) return;

    if (state.selectedServices.isEmpty) {
      state = state.copyWith(error: 'Selecione pelo menos um serviço.');
      return;
    }

    state = state.copyWith(isLoading: true, error: null);
    try {
      final booking = Booking(
        id: '', // Will be generated by repository
        userId: user.uid,
        vehicleId: state.selectedVehicle!.id,
        serviceIds: state.selectedServices.map((s) => s.id).toList(),
        scheduledTime: state.selectedTimeSlot!,
        status: BookingStatus.pending,
        totalPrice: state.totalPrice,
      );

      await ref.read(bookingRepositoryProvider).createBooking(booking);
      // Success
    } catch (e) {
      state = state.copyWith(error: e.toString());
    } finally {
      state = state.copyWith(isLoading: false);
    }
  }
}

final bookingControllerProvider =
    NotifierProvider.autoDispose<BookingController, BookingState>(() {
      return BookingController();
    });
