// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSijOdKJP2eD2QwAOqy5rV86EeGXx3QKE',
    appId: '1:992114921273:web:0b81f9a88b2e14610de2e8',
    messagingSenderId: '992114921273',
    projectId: 'autoolinda-5199e',
    authDomain: 'autoolinda-5199e.firebaseapp.com',
    databaseURL: 'https://autoolinda-5199e-default-rtdb.firebaseio.com',
    storageBucket: 'autoolinda-5199e.firebasestorage.app',
    measurementId: 'G-0J9B805MDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7g0wxdkSEF4D0Rw7GPc041svHWmupZfQ',
    appId: '1:992114921273:android:60d820df26a029550de2e8',
    messagingSenderId: '992114921273',
    projectId: 'autoolinda-5199e',
    databaseURL: 'https://autoolinda-5199e-default-rtdb.firebaseio.com',
    storageBucket: 'autoolinda-5199e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfWUUR5tXtuNSFY_82ccOejTo5BIaXVBU',
    appId: '1:992114921273:ios:2a90914ba4b1dab20de2e8',
    messagingSenderId: '992114921273',
    projectId: 'autoolinda-5199e',
    databaseURL: 'https://autoolinda-5199e-default-rtdb.firebaseio.com',
    storageBucket: 'autoolinda-5199e.firebasestorage.app',
    iosBundleId: 'com.aquaclean.aquacleanMobile',
  );
}
