// Photo upload and booking management
import 'dart:typed_data';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import '../../../features/booking/domain/availability.dart';
import '../../../features/booking/domain/booking.dart';
import '../../../features/booking/domain/service_package.dart';
import '../../../features/profile/domain/vehicle.dart';

class BookingRepository {
  final FirebaseFirestore _firestore;

  BookingRepository(this._firestore);

  // Mock Services for now
  // Services
  Stream<List<ServicePackage>> getServicesStream() {
    return _firestore.collection('services').snapshots().map((snapshot) {
      return snapshot.docs
          .map((doc) {
            try {
              final data = doc.data();
              return ServicePackage.fromJson({
                ...data,
                'id': doc.id,
                'title': data['title'] ?? 'Serviço sem título',
                'description': data['description'] ?? '',
                'price': (data['price'] as num?)?.toDouble() ?? 0.0,
                'durationMinutes': data['durationMinutes'] ?? 0,
              });
            } catch (e) {
              print('Error parsing service ${doc.id}: $e');
              return null;
            }
          })
          .whereType<ServicePackage>()
          .toList();
    });
  }

  Future<void> createService(ServicePackage service) async {
    final data = service.toJson();
    data.remove('id'); // ID is generated by Firestore
    await _firestore.collection('services').add(data);
  }

  Future<void> updateService(ServicePackage service) async {
    final data = service.toJson();
    data.remove('id'); // ID shouldn't be in the document data
    await _firestore.collection('services').doc(service.id).update(data);
  }

  Future<void> deleteService(String serviceId) async {
    await _firestore.collection('services').doc(serviceId).delete();
  }

  Future<ServicePackage?> getService(String serviceId) async {
    final doc = await _firestore.collection('services').doc(serviceId).get();
    if (!doc.exists) return null;
    return ServicePackage.fromJson({...doc.data()!, 'id': doc.id});
  }

  // Vehicles
  Stream<List<Vehicle>> getUserVehicles(String userId) {
    return _firestore
        .collection('vehicles')
        .where('userId', isEqualTo: userId)
        .snapshots()
        .map((snapshot) {
          return snapshot.docs
              .map((doc) {
                try {
                  final data = doc.data();
                  return Vehicle.fromJson({
                    ...data,
                    'id': doc.id,
                    'brand': data['brand'] ?? 'Marca desconhecida',
                    'model': data['model'] ?? 'Modelo desconhecido',
                    'plate': data['plate'] ?? '',
                    'color': data['color'] ?? '',
                    'type': data['type'] ?? 'sedan',
                  });
                } catch (e) {
                  print('Error parsing vehicle ${doc.id}: $e');
                  return null;
                }
              })
              .whereType<Vehicle>()
              .toList();
        });
  }

  Future<void> createVehicle(Vehicle vehicle, String userId) {
    // Exclude ID from data as it's generated by Firestore
    final data = vehicle.toJson();
    data.remove('id');

    return _firestore.collection('vehicles').add({
      ...data,
      'userId': userId,
      'created_at': FieldValue.serverTimestamp(),
    });
  }

  Future<Vehicle?> getVehicle(String vehicleId) async {
    final doc = await _firestore.collection('vehicles').doc(vehicleId).get();
    if (!doc.exists) return null;
    return Vehicle.fromJson({...doc.data()!, 'id': doc.id});
  }

  /// Upload photo using bytes (works on web and mobile)
  Future<String> uploadPhotoBytes(List<int> bytes, String path) async {
    try {
      final ref = FirebaseStorage.instance.ref().child(path);

      // Upload the bytes
      final uploadTask = ref.putData(
        Uint8List.fromList(bytes),
        SettableMetadata(contentType: 'image/jpeg'),
      );

      // Wait for upload to complete
      final snapshot = await uploadTask;

      // Get and return the download URL
      final downloadUrl = await snapshot.ref.getDownloadURL();
      print('📷 Photo uploaded (bytes): $downloadUrl');
      return downloadUrl;
    } catch (e) {
      print('❌ Error uploading photo bytes: $e');
      // Fallback to mock URL for testing if Storage is not configured
      if (e.toString().contains('storage') || e.toString().contains('bucket')) {
        print('⚠️ Using mock URL - Firebase Storage may not be configured');
        return 'https://picsum.photos/400/300?random=${DateTime.now().millisecondsSinceEpoch}';
      }
      throw Exception('Erro ao fazer upload da foto: $e');
    }
  }

  Future<void> addBookingPhoto(
    String bookingId,
    String photoUrl,
    bool isBefore,
  ) async {
    final field = isBefore ? 'beforePhotos' : 'afterPhotos';
    await _firestore.collection('appointments').doc(bookingId).update({
      field: FieldValue.arrayUnion([photoUrl]),
    });
  }

  Future<void> removeBookingPhoto(
    String bookingId,
    String photoUrl,
    bool isBefore,
  ) async {
    final field = isBefore ? 'beforePhotos' : 'afterPhotos';
    await _firestore.collection('appointments').doc(bookingId).update({
      field: FieldValue.arrayRemove([photoUrl]),
    });
  }

  // Appointments / Bookings
  Future<bool> checkAvailability(DateTime startTime) async {
    final dateStr = DateFormat('yyyy-MM-dd').format(startTime);
    final timeStr = DateFormat('HH:mm').format(startTime);

    // 1. Get Availability Config
    final availabilityDoc = await _firestore
        .collection('availability')
        .doc(dateStr)
        .get();

    if (!availabilityDoc.exists) {
      // Default: Open, 2 slots
      return true;
    }

    final availability = Availability.fromJson(availabilityDoc.data()!);
    if (!availability.isOpen) return false;

    final maxSlots = availability.slots[timeStr] ?? 2;

    // 2. Count Existing Appointments
    final appointmentsQuery = await _firestore
        .collection('appointments')
        .where('scheduledTime', isEqualTo: startTime.toIso8601String())
        .where('status', isNotEqualTo: 'cancelled')
        .get();

    return appointmentsQuery.docs.length < maxSlots;
  }

  Future<String> createBooking(Booking booking) async {
    print('🟢 Repository.createBooking: Calling Cloud Function...');

    try {
      final functions = FirebaseFunctions.instanceFor(
        region: 'southamerica-east1',
      );
      // Ensure region matches if different from default (us-central1)
      // functions.useFunctionsEmulator('localhost', 5001); // If testing locally

      final callable = functions.httpsCallable('createBooking');

      final payload = {
        'vehicleId': booking.vehicleId,
        'serviceIds': booking.serviceIds,
        'scheduledTime': booking.scheduledTime.toUtc().toIso8601String(),
        'staffNotes': booking.staffNotes,
      };

      print('🟢 Payload to send: $payload');
      print('   -> serviceIds type: ${booking.serviceIds.runtimeType}');
      print('   -> serviceIds content: ${booking.serviceIds}');

      // Convert proper types
      final result = await callable.call(payload);

      final data = result.data as Map<String, dynamic>;
      final bookingId = data['bookingId'] as String;

      print('✅ Repository: Booking created via function! ID: $bookingId');
      return bookingId;
    } on FirebaseFunctionsException catch (e) {
      print('❌ Cloud Function Error: ${e.code} - ${e.message}');
      print('❌ Details: ${e.details}');
      throw Exception(e.message ?? 'Erro ao processar agendamento.');
    } catch (e) {
      print('❌ Repository: Failed to create booking via function - $e');
      throw Exception('Erro ao processar agendamento: $e');
    }
  }

  Map<String, dynamic> _mapBookingData(String id, Map<String, dynamic> data) {
    try {
      final scheduledTime = data['scheduledTime'];
      String scheduledTimeStr;
      if (scheduledTime is Timestamp) {
        scheduledTimeStr = scheduledTime.toDate().toIso8601String();
      } else if (scheduledTime is String) {
        scheduledTimeStr = scheduledTime;
      } else {
        // Fallback for missing/invalid date
        scheduledTimeStr = DateTime.now().toIso8601String();
      }

      return {
        ...data,
        'id': id,
        'scheduledTime': scheduledTimeStr,
        'status': data['status'] ?? 'scheduled',
        'totalPrice': (data['totalPrice'] as num?)?.toDouble() ?? 0.0,
      };
    } catch (e) {
      // Re-throw so the caller can log the specific document ID if needed
      rethrow;
    }
  }

  Stream<List<Booking>> getUserBookings(String userId) {
    return _firestore
        .collection('appointments')
        .where('userId', isEqualTo: userId)
        .orderBy('scheduledTime', descending: true)
        .snapshots()
        .map((snapshot) {
          return snapshot.docs
              .map((doc) {
                try {
                  final data = doc.data();
                  final mappedData = _mapBookingData(doc.id, data);
                  return Booking.fromJson(mappedData);
                } catch (e) {
                  print('Error parsing booking ${doc.id}: $e');
                  return null;
                }
              })
              .whereType<Booking>()
              .toList();
        });
  }

  Stream<List<Booking>> getAllBookings() {
    return _firestore
        .collection('appointments')
        .orderBy('scheduledTime', descending: true)
        .snapshots()
        .map((snapshot) {
          return snapshot.docs
              .map((doc) {
                try {
                  return Booking.fromJson(_mapBookingData(doc.id, doc.data()));
                } catch (e) {
                  print('Error parsing booking ${doc.id}: $e');
                  return null;
                }
              })
              .whereType<Booking>()
              .toList();
        });
  }

  Stream<Booking> getBookingStream(String bookingId) {
    return _firestore.collection('appointments').doc(bookingId).snapshots().map(
      (doc) {
        if (!doc.exists) {
          throw Exception('Agendamento não encontrado');
        }
        return Booking.fromJson(_mapBookingData(doc.id, doc.data()!));
      },
    );
  }

  Future<void> updateBookingStatus(
    String bookingId,
    BookingStatus status, {
    String? message,
    String? actorId,
  }) {
    final Map<String, dynamic> updates = {'status': status.name};

    if (actorId != null) {
      final log = BookingLog(
        message: message ?? 'Status updated to ${status.name}',
        timestamp: DateTime.now(),
        actorId: actorId,
        status: status,
      );
      updates['logs'] = FieldValue.arrayUnion([log.toJson()]);
    }

    return _firestore.collection('appointments').doc(bookingId).update(updates);
  }

  Future<void> cancelBooking(
    String bookingId, {
    required String actorId,
  }) async {
    try {
      print('🟠 Repository.cancelBooking: Calling Cloud Function...');
      final functions = FirebaseFunctions.instanceFor(
        region: 'southamerica-east1',
      );
      final callable = functions.httpsCallable('cancelBooking');

      await callable.call({'bookingId': bookingId});
      print('✅ Repository: Booking cancelled via function.');
    } on FirebaseFunctionsException catch (e) {
      print('❌ Cloud Function Error: ${e.code} - ${e.message}');
      throw Exception(e.message ?? 'Erro ao cancelar agendamento.');
    } catch (e) {
      print('❌ Repository: Failed to cancel booking - $e');
      throw Exception('Erro ao cancelar agendamento: $e');
    }
  }

  Future<void> markAsRated(String bookingId, int rating, String? comment) {
    return _firestore.collection('appointments').doc(bookingId).update({
      'isRated': true,
      'rating': rating,
      'ratingComment': comment,
    });
  }

  Stream<List<Booking>> getBookingsForDate(DateTime date) {
    final startOfDay = DateTime(date.year, date.month, date.day);
    final endOfDay = startOfDay.add(const Duration(days: 1));

    print('🔍 [BookingRepo] getBookingsForDate: ${date.toIso8601String()}');
    print('   📅 Range: $startOfDay to $endOfDay');

    return _firestore
        .collection('appointments')
        .where(
          'scheduledTime',
          isGreaterThanOrEqualTo: Timestamp.fromDate(startOfDay),
        )
        .where('scheduledTime', isLessThan: Timestamp.fromDate(endOfDay))
        .orderBy('scheduledTime')
        .snapshots()
        .map((snapshot) {
          print(
            '✅ [BookingRepo] Query returned ${snapshot.docs.length} documents',
          );

          final bookings = snapshot.docs
              .map((doc) {
                try {
                  final booking = Booking.fromJson(
                    _mapBookingData(doc.id, doc.data()),
                  );
                  print('   📋 Parsed: ${doc.id} - ${booking.status}');
                  return booking;
                } catch (e) {
                  print('❌ [BookingRepo] Error parsing booking ${doc.id}: $e');
                  return null;
                }
              })
              .whereType<Booking>()
              .toList();

          print('✅ [BookingRepo] Returning ${bookings.length} valid bookings');
          return bookings;
        })
        .handleError((error, stackTrace) {
          print('❌ [BookingRepo] Stream ERROR: $error');
          print('❌ [BookingRepo] Stack: $stackTrace');
          throw error;
        });
  }

  /// Get all bookings within a date range (for history view)
  Future<List<Booking>> getBookingsInRange(DateTime start, DateTime end) async {
    final startOfDay = DateTime(start.year, start.month, start.day);
    final endOfDay = DateTime(
      end.year,
      end.month,
      end.day,
    ).add(const Duration(days: 1));

    final snapshot = await _firestore
        .collection('appointments')
        .where(
          'scheduledTime',
          isGreaterThanOrEqualTo: Timestamp.fromDate(startOfDay),
        )
        .where('scheduledTime', isLessThan: Timestamp.fromDate(endOfDay))
        .orderBy('scheduledTime', descending: true)
        .get();

    return snapshot.docs
        .map((doc) {
          try {
            return Booking.fromJson(_mapBookingData(doc.id, doc.data()));
          } catch (e) {
            print('Error parsing booking ${doc.id}: $e');
            return null;
          }
        })
        .whereType<Booking>()
        .toList();
  }

  Future<Booking?> getLastFinishedBookingForVehicle(
    String vehicleId,
    String userId,
  ) async {
    try {
      final query = await _firestore
          .collection('appointments')
          .where('userId', isEqualTo: userId)
          .where('vehicleId', isEqualTo: vehicleId)
          .where('status', isEqualTo: 'finished')
          .orderBy('scheduledTime', descending: true)
          .limit(1)
          .get();

      if (query.docs.isEmpty) return null;

      final doc = query.docs.first;
      return Booking.fromJson(_mapBookingData(doc.id, doc.data()));
    } catch (e) {
      print('Error fetching last booking for vehicle $vehicleId: $e');
      return null;
    }
  }

  /// Get the very latest booking for a user (used to detect confirmed payments)
  Future<Booking?> fetchLatestBooking(String userId) async {
    try {
      final query = await _firestore
          .collection('appointments')
          .where('userId', isEqualTo: userId)
          .orderBy(
            'scheduledTime',
            descending: true,
          ) // Assuming newly created usually has future time
          // Or we can rely on implicit creation order if we had createdAt.
          // For now, scheduledTime desc is good proxy if user just booked a future slot.
          .limit(1)
          .get();

      if (query.docs.isEmpty) return null;

      final doc = query.docs.first;
      return Booking.fromJson(_mapBookingData(doc.id, doc.data()));
    } catch (e) {
      print('Error fetching latest booking for user $userId: $e');
      return null;
    }
  }

  /// Find a specific booking for polling confirmation
  Future<Booking?> findBooking({
    required String userId,
    required String vehicleId,
    required DateTime scheduledTime,
  }) async {
    try {
      // Query by user and vehicle first (more robust than exact string match on time)
      final query = await _firestore
          .collection('appointments')
          .where('userId', isEqualTo: userId)
          .where('vehicleId', isEqualTo: vehicleId)
          //.where('status', isEqualTo: 'scheduled') // Optional, but let's find any status
          .get();

      if (query.docs.isEmpty) return null;

      // Filter in memory to handle potential string format differences
      for (final doc in query.docs) {
        final data = doc.data();
        final bookingTimeRaw = data['scheduledTime'];
        DateTime bookingTime;

        if (bookingTimeRaw is Timestamp) {
          bookingTime = bookingTimeRaw.toDate();
        } else if (bookingTimeRaw is String) {
          bookingTime = DateTime.parse(bookingTimeRaw);
        } else {
          continue;
        }

        // Check if times match (same year, month, day, hour, minute)
        // Ignoring seconds/millis which might differ purely due to formatting
        if (bookingTime.year == scheduledTime.year &&
            bookingTime.month == scheduledTime.month &&
            bookingTime.day == scheduledTime.day &&
            bookingTime.hour == scheduledTime.hour &&
            bookingTime.minute == scheduledTime.minute) {
          return Booking.fromJson(_mapBookingData(doc.id, data));
        }
      }

      return null;
    } catch (e) {
      print('Error finding specific booking: $e');
      return null;
    }
  }

  /// Check if a vehicle already has an active booking at the specified time
  Future<bool> hasExistingBookingForVehicle({
    required String vehicleId,
    required DateTime scheduledTime,
  }) async {
    try {
      final query = await _firestore
          .collection('appointments')
          .where('vehicleId', isEqualTo: vehicleId)
          .get();

      if (query.docs.isEmpty) return false;

      for (final doc in query.docs) {
        final data = doc.data();
        final status = data['status'] as String?;

        // Skip cancelled bookings
        if (status == 'cancelled') continue;

        final bookingTimeRaw = data['scheduledTime'];
        DateTime bookingTime;

        if (bookingTimeRaw is Timestamp) {
          bookingTime = bookingTimeRaw.toDate();
        } else if (bookingTimeRaw is String) {
          bookingTime = DateTime.parse(bookingTimeRaw);
        } else {
          continue;
        }

        // Check if same day and hour
        if (bookingTime.year == scheduledTime.year &&
            bookingTime.month == scheduledTime.month &&
            bookingTime.day == scheduledTime.day &&
            bookingTime.hour == scheduledTime.hour) {
          return true;
        }
      }

      return false;
    } catch (e) {
      print('Error checking existing booking: $e');
      return false;
    }
  }

  /// Get all bookings for a specific vehicle (for history view)
  Stream<List<Booking>> getVehicleBookings(String vehicleId, String userId) {
    return _firestore
        .collection('appointments')
        .where('userId', isEqualTo: userId)
        .where('vehicleId', isEqualTo: vehicleId)
        .snapshots()
        .map((snapshot) {
          final bookings = snapshot.docs
              .map((doc) {
                try {
                  return Booking.fromJson(_mapBookingData(doc.id, doc.data()));
                } catch (e) {
                  print('Error parsing booking ${doc.id}: $e');
                  return null;
                }
              })
              .whereType<Booking>()
              .toList();

          // Sort in Dart to avoid needing a Firestore composite index
          bookings.sort((a, b) => b.scheduledTime.compareTo(a.scheduledTime));
          return bookings;
        });
  }
}

final bookingRepositoryProvider = Provider<BookingRepository>((ref) {
  return BookingRepository(FirebaseFirestore.instance);
});

final servicesProvider = StreamProvider<List<ServicePackage>>((ref) {
  return ref.watch(bookingRepositoryProvider).getServicesStream();
});

final userVehiclesProvider = StreamProvider.family<List<Vehicle>, String>((
  ref,
  userId,
) {
  return ref.watch(bookingRepositoryProvider).getUserVehicles(userId);
});

final userBookingsProvider = StreamProvider.family<List<Booking>, String>((
  ref,
  userId,
) {
  return ref.watch(bookingRepositoryProvider).getUserBookings(userId);
});

final allBookingsProvider = StreamProvider<List<Booking>>((ref) {
  return ref.watch(bookingRepositoryProvider).getAllBookings();
});

final bookingStreamProvider = StreamProvider.family<Booking, String>((
  ref,
  bookingId,
) {
  return ref.watch(bookingRepositoryProvider).getBookingStream(bookingId);
});

final bookingsForDateProvider = StreamProvider.family<List<Booking>, DateTime>((
  ref,
  date,
) {
  return ref.watch(bookingRepositoryProvider).getBookingsForDate(date);
});

final todayBookingsProvider = StreamProvider<List<Booking>>((ref) {
  return ref
      .watch(bookingRepositoryProvider)
      .getBookingsForDate(DateTime.now());
});

final vehicleProvider = FutureProvider.family<Vehicle?, String>((
  ref,
  vehicleId,
) {
  return ref.watch(bookingRepositoryProvider).getVehicle(vehicleId);
});

final lastVehicleBookingProvider =
    FutureProvider.family<Booking?, (String, String)>((ref, args) {
      final (vehicleId, userId) = args;
      return ref
          .watch(bookingRepositoryProvider)
          .getLastFinishedBookingForVehicle(vehicleId, userId);
    });

/// Provider for streaming all bookings of a specific vehicle (history)
final vehicleBookingsProvider =
    StreamProvider.family<List<Booking>, (String, String)>((ref, args) {
      final (vehicleId, userId) = args;
      return ref
          .watch(bookingRepositoryProvider)
          .getVehicleBookings(vehicleId, userId);
    });
