import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import '../../../features/booking/domain/availability.dart';
import '../../../features/booking/domain/booking.dart';
import '../../../features/booking/domain/service_package.dart';
import '../../../features/profile/domain/vehicle.dart';

class BookingRepository {
  final FirebaseFirestore _firestore;

  BookingRepository(this._firestore);

  // Mock Services for now
  Future<List<ServicePackage>> getServices() async {
    await Future.delayed(const Duration(milliseconds: 500));
    return [
      const ServicePackage(
        id: 'basic',
        title: 'Lavagem Simples',
        description: 'Lavagem externa e secagem',
        price: 40.0,
        durationMinutes: 45,
      ),
      const ServicePackage(
        id: 'premium',
        title: 'Lavagem Completa',
        description: 'Lavagem interna e externa, cera e pretinho',
        price: 60.0,
        durationMinutes: 60,
        isPopular: true,
      ),
      const ServicePackage(
        id: 'deluxe',
        title: 'Lavagem Deluxe',
        description: 'Completa + polimento e higienização de bancos',
        price: 100.0,
        durationMinutes: 90,
      ),
    ];
  }

  // Vehicles
  Stream<List<Vehicle>> getUserVehicles(String userId) {
    return _firestore
        .collection('vehicles')
        .where('userId', isEqualTo: userId)
        .snapshots()
        .map((snapshot) {
          return snapshot.docs.map((doc) {
            final data = doc.data();
            // Ensure ID is passed if not in data
            return Vehicle.fromJson({...data, 'id': doc.id});
          }).toList();
        });
  }

  Future<void> createVehicle(Vehicle vehicle, String userId) {
    // Exclude ID from data as it's generated by Firestore
    final data = vehicle.toJson();
    data.remove('id');

    return _firestore.collection('vehicles').add({
      ...data,
      'userId': userId,
      'created_at': FieldValue.serverTimestamp(),
    });
  }

  Future<Vehicle?> getVehicle(String vehicleId) async {
    final doc = await _firestore.collection('vehicles').doc(vehicleId).get();
    if (!doc.exists) return null;
    return Vehicle.fromJson({...doc.data()!, 'id': doc.id});
  }

  // Appointments / Bookings
  Future<bool> checkAvailability(DateTime startTime) async {
    final dateStr = DateFormat('yyyy-MM-dd').format(startTime);
    final timeStr = DateFormat('HH:mm').format(startTime);

    // 1. Get Availability Config
    final availabilityDoc = await _firestore
        .collection('availability')
        .doc(dateStr)
        .get();

    if (!availabilityDoc.exists) {
      // Default: Open, 2 slots
      return true;
    }

    final availability = Availability.fromJson(availabilityDoc.data()!);
    if (!availability.isOpen) return false;

    final maxSlots = availability.slots[timeStr] ?? 2;

    // 2. Count Existing Appointments
    final appointmentsQuery = await _firestore
        .collection('appointments')
        .where('scheduledTime', isEqualTo: startTime.toIso8601String())
        .where('status', isNotEqualTo: 'cancelled')
        .get();

    return appointmentsQuery.docs.length < maxSlots;
  }

  Future<String> createBooking(Booking booking) async {
    // 1. Check for conflicts (Best Effort)
    final querySnapshot = await _firestore
        .collection('appointments')
        .where(
          'scheduledTime',
          isEqualTo: booking.scheduledTime.toIso8601String(),
        )
        .where(
          'status',
          whereIn: [
            BookingStatus.pending.name,
            BookingStatus.confirmed.name,
            BookingStatus.washing.name,
            BookingStatus.drying.name,
          ],
        )
        .get();

    if (querySnapshot.docs.isNotEmpty) {
      throw Exception(
        'Horário indisponível. Por favor, escolha outro horário.',
      );
    }

    // 2. Create Booking Document
    final docRef = _firestore.collection('appointments').doc();
    final bookingWithId = booking.copyWith(id: docRef.id);

    await docRef.set({
      ...bookingWithId.toJson(),
      'status': bookingWithId.status.name,
      'scheduledTime': bookingWithId.scheduledTime.toIso8601String(),
    });

    return docRef.id;
  }

  Stream<List<Booking>> getUserBookings(String userId) {
    return _firestore
        .collection('appointments')
        .where('userId', isEqualTo: userId)
        .orderBy('scheduledTime', descending: true)
        .snapshots()
        .map((snapshot) {
          return snapshot.docs.map((doc) {
            final data = doc.data();
            return Booking.fromJson({...data, 'id': doc.id});
          }).toList();
        });
  }

  Stream<List<Booking>> getAllBookings() {
    return _firestore
        .collection('appointments')
        .orderBy('scheduledTime', descending: true)
        .snapshots()
        .map((snapshot) {
          return snapshot.docs.map((doc) {
            final data = doc.data();
            return Booking.fromJson({...data, 'id': doc.id});
          }).toList();
        });
  }

  Stream<Booking> getBookingStream(String bookingId) {
    return _firestore.collection('appointments').doc(bookingId).snapshots().map(
      (doc) {
        if (!doc.exists) {
          throw Exception('Agendamento não encontrado');
        }
        return Booking.fromJson({...doc.data()!, 'id': doc.id});
      },
    );
  }

  Future<void> updateBookingStatus(String bookingId, BookingStatus status) {
    return _firestore.collection('appointments').doc(bookingId).update({
      'status': status.name,
    });
  }

  Stream<List<Booking>> getBookingsForDate(DateTime date) {
    final startOfDay = DateTime(date.year, date.month, date.day);
    final endOfDay = startOfDay.add(const Duration(days: 1));

    return _firestore
        .collection('appointments')
        .where(
          'scheduledTime',
          isGreaterThanOrEqualTo: startOfDay.toIso8601String(),
        )
        .where('scheduledTime', isLessThan: endOfDay.toIso8601String())
        .orderBy('scheduledTime')
        .snapshots()
        .map((snapshot) {
          return snapshot.docs.map((doc) {
            final data = doc.data();
            return Booking.fromJson({...data, 'id': doc.id});
          }).toList();
        });
  }
}

final bookingRepositoryProvider = Provider<BookingRepository>((ref) {
  return BookingRepository(FirebaseFirestore.instance);
});

final servicesProvider = FutureProvider<List<ServicePackage>>((ref) {
  return ref.watch(bookingRepositoryProvider).getServices();
});

final userVehiclesProvider = StreamProvider.family<List<Vehicle>, String>((
  ref,
  userId,
) {
  return ref.watch(bookingRepositoryProvider).getUserVehicles(userId);
});

final userBookingsProvider = StreamProvider.family<List<Booking>, String>((
  ref,
  userId,
) {
  return ref.watch(bookingRepositoryProvider).getUserBookings(userId);
});

final allBookingsProvider = StreamProvider<List<Booking>>((ref) {
  return ref.watch(bookingRepositoryProvider).getAllBookings();
});

final bookingStreamProvider = StreamProvider.family<Booking, String>((
  ref,
  bookingId,
) {
  return ref.watch(bookingRepositoryProvider).getBookingStream(bookingId);
});

final todayBookingsProvider = StreamProvider<List<Booking>>((ref) {
  return ref
      .watch(bookingRepositoryProvider)
      .getBookingsForDate(DateTime.now());
});

final vehicleProvider = FutureProvider.family<Vehicle?, String>((
  ref,
  vehicleId,
) {
  return ref.watch(bookingRepositoryProvider).getVehicle(vehicleId);
});
